#ifndef FAST_H
#define FAST_H

#include <stdint.h>

/* Solve the state "PPPPPPPOOOOOOO" (same 14-digit format as solver.c).
 * Writes move indices 0..8 (R R2 R' B B2 B' D D2 D') to path[0..len-1]
 * and returns len (0..11), or -1 if the input is not a valid state.
 * path must hold at least 11 entries. */
int fast_solve(const char *in, uint8_t *path);

/* Children generated by the last fast_solve call. */
extern uint32_t fast_nodes;

#endif
