"""Write mine/tables.s: the lookup tables in the plainest layout.

Input is opt/tables.h (generated by opt/gen_tables.c, which also checks
gates H1, H2 and H4 on these tables).  Layout of the output, all
little endian, faces stored one after another (face 0 = R, 1 = B, 2 = D):

  pm          3 * 5040 halfwords   next perm after one quarter turn
  om          3 * 729  halfwords   next orient after one quarter turn
  lm          3 * 210  bytes       next place after one quarter turn
  place_base  210 words            place * 729, so no multiply is needed
  pdb_perm    5040 bytes           one heuristic value per perm
  pdb_ol      76545 bytes          153090 values, two per byte, even index
                                   in the low nibble; index = place * 729
                                   + orient

Total 117,669 bytes, under the 131,072 byte limit.
Generated tables are data; this script is not part of the assembly.
"""
import re
import sys

src = open(sys.argv[1]).read()
arrays = {}
for m in re.finditer(r"static const (\w+) (\w+)\[(\d+)\] = \{(.*?)\};", src, re.S):
    typ, name, n, body = m.groups()
    vals = [int(x) for x in re.findall(r"\d+", body)]
    assert len(vals) == int(n), (name, len(vals), n)
    arrays[name] = vals


def emit(out, label, directive, vals, per_line):
    out.append(f"{label}:")
    for i in range(0, len(vals), per_line):
        out.append(f"    {directive} " + ", ".join(str(v) for v in vals[i:i + per_line]))


perm_h = []
for b in arrays["pdb_perm"]:
    perm_h += [b & 15, b >> 4]
perm_h = perm_h[:5040]

out = ["# Generated by opt/make_simple_tables.py from opt/tables.h. Do not edit.",
       "# Data only; layout is described in that script.", ".align 2"]
emit(out, "place_base", ".word", arrays["place_base"], 10)
emit(out, "pm", ".half", arrays["pm0"] + arrays["pm1"] + arrays["pm2"], 16)
emit(out, "om", ".half", arrays["om0"] + arrays["om1"] + arrays["om2"], 16)
emit(out, "lm", ".byte", arrays["lm0"] + arrays["lm1"] + arrays["lm2"], 20)
emit(out, "pdb_perm", ".byte", perm_h, 20)
emit(out, "pdb_ol", ".byte", arrays["pdb_ol"], 20)
open(sys.argv[2], "w").write("\n".join(out) + "\n")
total = (4 * 210 + 2 * 3 * 5040 + 2 * 3 * 729 + 3 * 210 + 5040
         + len(arrays["pdb_ol"]))
print(f"wrote {sys.argv[2]}: {total} bytes of tables")
